FileshareSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('share/', include('share.urls')),
    path('users/', include('users.urls')),
    path('', include('movie.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path
from . import views as movie_views


app_name = "movie"
urlpatterns = [
    path('create/', movie_views.CreateView.as_view(), name="create"),
    path('popular/', movie_views.popular, name="popular"),
    path('search/', movie_views.search, name="search"),
    path('detail/<pk>/', movie_views.MovieDetailView.as_view(), name="detail"),
    path('', movie_views.HomeListView.as_view(), name="home"),
]

share/urls.py
from django.urls import path
from . import views


app_name = "share"
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('upload/', views.UploadView.as_view(), name="upload"),
    path('detail/<int:pk>/', views.DetailView.as_view(), name="detail"),
    path('download/<int:videoId>/', views.download, name="download"),
    path('search/', views.ListView.as_view(), name="search"),
    path('delete/<int:videoId>', views.delete, name="delete"),
    path('image/', views.image, name="image"),
    path('checkpagination/', views.check_pagination, name="checkpagination"),
]

users/urls.py
from django.urls import path
from . import views as user_views
from django.contrib.auth import views as auth_views

app_name = "users"
urlpatterns = [
    path('register/', user_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
    path('profile/', user_views.ProfileListView.as_view(), name="profile"),
]

share/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.


class VideoInfo(models.Model):
    aws_file_name = models.CharField(max_length=256, verbose_name="AWSFilename", default="")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    download_count = models.IntegerField(verbose_name="Access Count", default=0)
    code = models.CharField(max_length=8, verbose_name="Code")
    upload_time = models.DateTimeField(default=datetime.now, verbose_name="Upload Time")
    download_path = models.CharField(max_length=256, verbose_name="Download Path")
    file_name = models.CharField(max_length=256, verbose_name="Filename", default="")
    file_size = models.CharField(max_length=10, verbose_name="File Size_KB")
    upload_ip = models.CharField(max_length=64, verbose_name="IP Address", default="")

    class Meta:
        verbose_name = "Video Information"
        db_table = "VideoInfo"

    def __str__(self): # the name we are going to see while query
        return self.file_name

share/views.py
import os
import random
import string

from django.core.exceptions import ValidationError
from django.core.files.storage import default_storage, FileSystemStorage
from django.db.models import F
from django.http import HttpResponseRedirect, FileResponse, Http404, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import View, DetailView, ListView
from .models import VideoInfo
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import messages
from django.core.paginator import Paginator


# Create your views here.

def image(request):
    return render(request, 'share/image.html', {'imageurl': default_storage.url('liangandy/django-dark.width-808.png')})


class IndexView(ListView):
    model = VideoInfo
    template_name = 'share/mainpage.html'
    context_object_name = 'videoinfo'
    ordering = ['-upload_time']
    paginate_by = 8


class UploadView(View):
    @method_decorator(login_required)
    def post(self, request):
        max_size = 4096 # 4MB = 4096KB
        if request.FILES:
            file = request.FILES.get("file")
            size = int(int(file.size) / 1024)
            try:
                print(size)
                if size > max_size:
                    raise ValidationError('File too large. Size should not exceed 4 MB.')
            except ValidationError:
                messages.warning(request, f'Error: File too large. Size should not exceed 4 MB.')
                return render(request, 'share/mainpage.html', {'error_message': 'Size should not exceed 30 MB'})
            filename = file.name
            aws_filename = request.user.username+'/'+filename
            '''
            store to /media/
            
            fs = FileSystemStorage()
            store_name=fs.save(request.user.username+'/'+filename, file)
            store_url=fs.url(store_name)
            '''
            print('prepare upload')
            if default_storage.exists(aws_filename):
                print('file already exist')
                messages.warning(request, f'Error: Failed to store due to duplicate file name. '
                                            f'Here is the file you uploaded before.')
                return render(request, 'share/mainpage.html', {'error_message': 'Failed to store due to duplicate file '
                                                                'name. Here is the file you uploaded before.'})
            else:
                # s3file = default_storage.open(filepath, 'w')
                default_storage.save(aws_filename, file)
                #s3file.close()
                upload = VideoInfo(
                    code=''.join(random.sample(string.digits, 8)),
                    file_name=filename,
                    download_path=default_storage.url(request.user.username+'/'+filename),
                    file_size=size,
                    upload_ip=str(request.META['REMOTE_ADDR']),
                    user=request.user,
                    aws_file_name=aws_filename
                )
                upload.save()

            '''Low level approach
            
            with open('share/static/share/file/' + filename, 'wb') as destination:
                for chunk in file.chunks():
                    destination.write(chunk)
            '''
        return HttpResponseRedirect(reverse('share:detail',
                                            args=(int(VideoInfo.objects.get(aws_file_name=aws_filename).id),)))


class DetailView(DetailView):
    model = VideoInfo
    template_name = 'share/detail.html'


class ListView(ListView):
    template_name = 'share/mainpage.html'
    context_object_name = 'videoinfo'
    paginate_by = 6
    # print('here')

    def get_queryset(self):
        # print(self.kwargs['filename'])
        # print(VideoInfo.objects.all())
        # return VideoInfo.objects.filter(file_name__icontains=self.kwargs['filename'])
        videoSet = VideoInfo.objects.annotate(
            similarity=TrigramSimilarity('file_name', self.request.GET.get('search')),
        ).filter(similarity__gt=0.3).order_by('-similarity')
        # print(videoSet)
        return videoSet


def download(request, videoId):
    video_info = get_object_or_404(VideoInfo, pk=videoId)
    '''
    download from localhost
    file_path = ''.join([settings.MEDIA_ROOT, '/', video_info.file_name])
    '''
    print('media/'+video_info.download_path)
    if default_storage.exists(video_info.aws_file_name):
        f = default_storage.open(video_info.aws_file_name, 'r')
        response = FileResponse(f)
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = ''.join(['attachment; filename=', video_info.file_name])
        video_info.download_count = F('download_count') + 1
        video_info.save()
        f.close()
        return response
    else:
        print('not found ')
    raise Http404


def delete(request, videoId):
    if request.method == 'POST':
        delete_item = get_object_or_404(VideoInfo, pk=videoId)  # either pk or id is fine
        if delete_item.user == request.user:
            delete_item.delete()
            default_storage.delete(delete_item.aws_file_name)
            return JsonResponse({'status': 'success', 'delete_item': delete_item.file_name})
        else:
            return JsonResponse({'status': 'fail', 'reason': 'User Not Authorized'})


@login_required
def check_pagination(request):
    if request.method == "GET":
        cur_user_file = VideoInfo.objects.filter(user=request.user)
        p = Paginator(cur_user_file, 10)
        return JsonResponse({'num_pages': p.num_pages})

share/templates/share/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>File Upload Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
</head>
<body>
    {% include './upload.html' %}
    {% block content%}
    {% endblock%}
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
</body>

</html>

share/templates/share/detail.html
{% extends './base.html' %}
{% block content%}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'share/CSS/detail.css' %}">
{% if messages %}
        {% for message in messages %}
            <div class="alert">
            {{ message }}
            </div>
        {% endfor %}
    {% endif %}


<table class="table text-white d-flex justify-content-center align-items-center mt-5">
    <tbody>
        <tr>
          <th>File Name</th>
            <td>{{videoinfo.file_name}}</td>
        </tr>
        <tr>
          <th>Upload Time</th>
            <td>{{videoinfo.upload_time}}</td>
        </tr>
        <tr>
          <th>File Size</th>
            <td>{{videoinfo.file_size}} KB</td>
        </tr>
        <tr>
        <tr>
          <th>User IP</th>
            <td>{{videoinfo.upload_ip}}</td>
        </tr>
          <th>#Download</th>
            <td>{{videoinfo.download_count}}</td>
        </tr>
        <tr>
          <th>Download Path</th>
            <td><a class="download-link" href="{% url 'share:download' videoinfo.id %}">
                {{videoinfo.file_name}}
            </a></td>
        </tr>
        <tr>
            <th></th>
            <td></td>
        </tr>
    </tbody>
</table>
{% endblock %}

share/templates/share/image.html
<img src="{{imageurl}}">

share/templates/share/list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'share/CSS/list.css' %}">
<div class="file-list">
    <div class="file-title">
        <div class="file-id">ID</div>
        <div class="file-name" >File Name</div>
        <div class="file-size" >File Size</div>
        <div class="file-download-count" >Visits</div>
        <div class="file-date" >File Date</div>
        <div class="file-link" >File Link</div>
        <div class="file-button"></div>
    </div>
    {% for info in videoinfo %}
    <div class="file-content">
        <div class="file-id">{{info.pk}}</div>
        <div class="file-name" >{{ info.file_name }}</div>
        <div class="file-size" >{{ info.file_size }} KB</div>
        <div class="file-download-count" >{{ info.download_count }}</div>
        <div class="file-date" >{{ info.upload_time }}</div>
        <div class="file-link" >{{info.download_path}}</div>
        <a class="btn btn-outline-secondary btn-sm file-download-link " href="{% url 'share:download' info.id %}">
            Download
        </a>
    </div>
    {% endfor%}
    <div class="mt-3">
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-1 btn-sm" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-1 btn-sm" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif%}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-outline-info mb-1 btn-sm" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num > page_obj.number|add:'3'%}
                <a class="btn btn-outline-info mb-1 btn-sm" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-1 btn-sm" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-1 btn-sm" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif%}
    {% endif %}
    </div>
</div>

share/templates/share/mainpage.html
{% extends './base.html'%}

{% block content%}
    {% include './search.html' %}
    {% include './list.html' %}
{% endblock%}

share/templates/share/search.html
{% block search %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'share/CSS/search.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% if messages %}
        {% for message in messages %}
            <div class="alert">
            {{ message }}
            </div>
        {% endfor %}
    {% endif %}
<div class="search-box d-flex flex-column">
    <form class="search-form" action="{% url 'share:search'%}">
        <input type="text" placeholder="Search.." name="search">
        <button class="rounded-75 ml-1"type="submit"><i class="fa fa-search"></i></button>
    </form>
    <p class="mt-3 text-muted">File size is limited to 4 MB for now due to restriction on Heroku.
        I will fix that later by uploading files directly to AWS S3.
    </p>
</div>
{% endblock %}

share/templates/share/upload.html
{% block content%}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'share/CSS/upload.css' %}">
<nav class='nav-container'>
    {% if user.is_authenticated %}
    <h1 class="welcome-msg">Welcome, {{user.username}}</h1>
    <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'share:index' %}">Main Page</a>
    <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'users:logout' %}">Logout</a>
    <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'users:profile' %}">Profile</a>
    <form class="upload-form" enctype="multipart/form-data" action="{% url 'share:upload'%}" method="post">
        {% csrf_token %}
        <input type="file" id="upload-input" name="file" hidden="hidden" />
        <button type="button" class="btn btn-outline-info mr-2 btn-sm upload-button">Upload</button>
    </form>
    {% else %}
    <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'share:index' %}">Main Page</a>
    <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'users:login' %}">Login</a>
    <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'users:register' %}">Register</a>
    {% endif %}
</nav>

{% load static %}
<script type="text/javascript" src="{% static 'share/JavaScript/upload.js' %}"></script>
<!--<script type="text/javascript">
    const upload = (file) => {
        const formData = new FormData();
        formData.append('file', file);
        formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
        fetch('{% url 'share:upload'%}', {
            method: 'POST',
            body: formData,
        })
        .then(response => {
            if (response.redirected) {
                window.location.href = response.url;
            }
        })
        .catch(error => console.log(error));
    };

    document.querySelector(".upload-button").addEventListener("click", function() {
        console.log('clicked')
        document.getElementById("upload-input").click();
    });

    const input = document.getElementById("upload-input")
    input.onchange = function() {
        upload(input.files[0])
    };
</script>-->
{% endblock %}