FileshareSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('share/', include('share.urls')),
    path('users/', include('users.urls')),
    path('', include('movie.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path
from . import views as movie_views


app_name = "movie"
urlpatterns = [
    path('create/', movie_views.CreateView.as_view(), name="create"),
    path('popular/', movie_views.popular, name="popular"),
    path('search/', movie_views.search, name="search"),
    path('detail/<pk>/', movie_views.MovieDetailView.as_view(), name="detail"),
    path('', movie_views.HomeListView.as_view(), name="home"),
]

share/urls.py
from django.urls import path
from . import views


app_name = "share"
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('upload/', views.UploadView.as_view(), name="upload"),
    path('detail/<int:pk>/', views.DetailView.as_view(), name="detail"),
    path('download/<int:videoId>/', views.download, name="download"),
    path('search/', views.ListView.as_view(), name="search"),
    path('delete/<int:videoId>', views.delete, name="delete"),
    path('image/', views.image, name="image"),
    path('checkpagination/', views.check_pagination, name="checkpagination"),
]

users/urls.py
from django.urls import path
from . import views as user_views
from django.contrib.auth import views as auth_views

app_name = "users"
urlpatterns = [
    path('register/', user_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
    path('profile/', user_views.ProfileListView.as_view(), name="profile"),
]

movie/models.py
from django.db import models
from datetime import datetime, date
from django.contrib.auth.models import User

# Create your models here.


class MovieReview(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    movie_name = models.CharField(max_length=256, verbose_name="Movie Name", default="")
    release_date = models.DateField(default=date.today, verbose_name="Release Date")
    rating = models.DecimalField(max_digits=2, decimal_places=1)
    overview = models.TextField()
    cover = models.ImageField(upload_to="Movie", blank=True)

    class Meta:
        verbose_name = "Movie Information"
        db_table = "Movie Info"

    def __str__(self): # the name we are going to see while query
        return self.movie_name

movie/forms.py
from django import forms
from .models import MovieReview


class MovieForm(forms.ModelForm):

    class Meta:
        model = MovieReview
        fields = ['movie_name', 'release_date', 'rating', 'overview', 'cover']

movie/views.py
from io import BytesIO

from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, DetailView
from django.views.generic.base import View
from .forms import MovieForm
from .models import MovieReview

import requests
import os

baseURL = 'https://api.themoviedb.org/3'
api_key = os.environ.get("MOVIE_DB_API")


class CreateView(View):
    def get(self, request):
        form = MovieForm
        return render(request, "movie/create.html", {"form": form})

    def post(self, request):
        cover = request.FILES.get('cover', False)
        form = MovieForm(request.POST, request.FILES)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.creator = request.user
            if cover:
                print("cover!")
                movie.save()
                return redirect('/create/')
            else:
                poster_path = request.POST.get("poster_path")
                pic_url = "https://image.tmdb.org/t/p/w300"+poster_path
                pic_request = requests.get(pic_url, stream=True)
                if pic_request.status_code == requests.codes.ok:
                    file_name = request.POST.get("movie_name")+".jpg"
                    fp = BytesIO()
                    fp.write(pic_request.content)
                    movie.cover.save(file_name, fp)
            #id = MovieReview.objects.get(movie_name=movie.movie_name).id
            id = movie.pk
            return HttpResponseRedirect(reverse('movie:detail', args=(id, )))


class HomeListView(ListView):
    model = MovieReview
    template_name = 'movie/home.html'
    context_object_name = "MovieCollection"
    paginate_by = 3


class MovieDetailView(DetailView):
    model = MovieReview
    template_name = 'movie/detail.html'
    context_object_name = "moviereview"



def popular(request):
    result = GetMovieInfo(route="/movie/popular", max=20)
    return JsonResponse(result)


def search(request):
    queryString = request.GET.dict()
    # print(request.GET)
    result = GetMovieInfo(route="/search/movie", params=queryString)
    return JsonResponse(result)


def GetMovieInfo(route, max=-1, params={}):
    PARAMS = {'api_key': api_key}
    PARAMS.update(params)
    URL = baseURL + route
    r = requests.get(url=URL, params=PARAMS)
    data = r.json()
    result = {}
    if max != -1:
        length = max
    else:
        length = len(data["results"])
    for i in range(length):
        temp_list = [{
            "release_date": data["results"][i]["release_date"],
            "rating": data["results"][i]["vote_average"],
            "movie_name": data["results"][i]["title"],
            "overview": data["results"][i]["overview"],
            "poster_path": data["results"][i]["poster_path"],
        }]
        result[str(i)] = temp_list
    hashmap = {}
    for key, value in result.items():
        if value[0]["movie_name"] in hashmap:
            hashmap[value[0]["movie_name"]].append(int(key))
        else:
            hashmap[value[0]["movie_name"]] = [int(key)]
    for value in hashmap.values():
        if len(value) > 1:
            for i in value:
                result[str(i)][0]["movie_name"] += " (" + result[str(i)][0]["release_date"] + ")"
    return result

movie/templates/movie/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
{% load static %}
<body class="d-flex flex-column" style="background:url({% static 'users/Images/background.jpg'%});">
    <div class="align-self-end d-flex justify-content-start align-items-md-start pt-5 mb-5" style="width: 88.5%;">
        {% if user.is_authenticated %}
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'movie:home' %}">Main Page</a>
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'users:logout' %}">Logout</a>
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'users:profile' %}">Profile</a>
        <a class='btn btn-outline-info  mr-5 btn-sm' href="{% url 'movie:create' %}">Create</a>
        {% else %}
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'movie:home' %}">Main Page</a>
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'users:login' %}">Login</a>
        <a class='btn btn-outline-info  mr-5 btn-sm' href="{% url 'users:register' %}">Register</a>
        {% endif %}
    </div>

    <div class="d-flex flex-direction-row justify-content-sm-center" >
        {% load crispy_forms_tags %}
        <div class="w-50" >
            <form action="/create/" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group movie-create-form">
                    <legend class="border-bottom mb-4">New Movie</legend>
                    {{ form | crispy }}

                </fieldset>
                <input type="hidden" id="download-url" name="poster_path">
                <div class="form-group signup-btn">
                    <button class="btn btn-success" type="submit">Create</button>
                </div>
            </form>
        </div>
        <div class="w-25 ml-4">
            <legend class="border-bottom mb-4">Movie Search</legend>
            <div class="d-flex">
                <input type="text" class="form-control movie-search-input" placeholder="Search" name="search">
                <button class="btn btn-success movie-search-button"><i class="fa fa-search"></i></button>
            </div>
            <div class="display-result">

            </div>
    </div>
    </div>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static '/JavaScript/create.js' %}"></script>
</body>
</html>

movie/templates/movie/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie Recommandation</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
</head>
{% load static %}
<body class="d-flex flex-column" style="background:url({% static 'users/Images/background.jpg'%});">
    <div class="align-self-end d-flex justify-content-start align-items-md-start pt-5" style="width: 88.5%;">
        {% if user.is_authenticated %}
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'movie:home' %}">Main Page</a>
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'users:logout' %}">Logout</a>
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'users:profile' %}">Profile</a>
        <a class='btn btn-outline-info  mr-5 btn-sm' href="{% url 'movie:create' %}">Create</a>
        {% else %}
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'movie:home' %}">Main Page</a>
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'users:login' %}">Login</a>
        <a class='btn btn-outline-info  mr-5 btn-sm' href="{% url 'users:register' %}">Register</a>
        {% endif %}
    </div>
    <div class="d-flex flex-direction-row justify-content-sm-center">
        <div class="w-50 mt-3 mr-3">
            <h2 class="border-bottom pt-5 mb-5">{{moviereview.movie_name}}</h2>
            <div class="mb-4">
                <h4>Release date: </h4>
                <p>{{moviereview.release_date}}</p>
            </div>
            <div class="mb-4">
                <h4>Rating: </h4>
                <p>{{moviereview.rating}}</p>
            </div>
            <div class="mb-4">
                <h4>Overview: </h4>
                <p>{{moviereview.overview}}</p>
            </div>



        </div>
        <div class="w-25 mt-3 ml-3">
            <img src="{{moviereview.cover.url}}">
        </div>
    </div>


    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
</body>
</html>

movie/templates/movie/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie Home</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
</head>
{% load static%}
<body class="d-flex flex-column" style="background:url({% static 'users/Images/background.jpg'%});">
    <div class="align-self-end d-flex justify-content-start align-items-md-start pt-5 mb-5" style="width: 88.5%;">
        {% if user.is_authenticated %}
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'movie:home' %}">Main Page</a>
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'users:logout' %}">Logout</a>
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'users:profile' %}">Profile</a>
        <a class='btn btn-outline-info  mr-5 btn-sm' href="{% url 'movie:create' %}">Create</a>
        {% else %}
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'movie:home' %}">Main Page</a>
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'users:login' %}">Login</a>
        <a class='btn btn-outline-info  mr-5 btn-sm' href="{% url 'users:register' %}">Register</a>
        {% endif %}
    </div>
    <div>
        <div class="d-flex flex-row justify-content-around">
            {% for movie in MovieCollection %}
            <div class="p-1 d-flex flex-column justify-content-center align-items-center">
                <a href="{% url 'movie:detail' movie.id%}">
                    <img src="{{movie.cover.url}}"
                         class="img-thumbnail rounded mx-auto d-block"
                         style="max-width:60%;max-height:60%;">
                </a>

                <h4>{{movie.movie_name}}</h4>
            </div>
            {% endfor%}
        </div>
    </div>
    <div class="mt-3 d-flex justify-content-center">
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-1 btn-sm" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-1 btn-sm" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif%}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-outline-info mb-1 btn-sm" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num > page_obj.number|add:'3'%}
                <a class="btn btn-outline-info mb-1 btn-sm" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-1 btn-sm" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-1 btn-sm" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif%}
    {% endif %}
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
</body>
</html>

movie/templates/movie/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <nav class='nav-container'>
        {% if user.is_authenticated %}
        <h1 class="welcome-msg">Welcome, {{user.username}}</h1>
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'share:index' %}">Main Page</a>
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'users:logout' %}">Logout</a>
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'users:profile' %}">Profile</a>
        <form class="upload-form" enctype="multipart/form-data" action="{% url 'share:upload'%}" method="post">
            {% csrf_token %}
            <input type="file" id="upload-input" name="file" hidden="hidden" />
            <button type="button" class="btn btn-outline-info mr-2 btn-sm upload-button">Upload</button>
        </form>
        {% else %}
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'share:index' %}">Main Page</a>
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'users:login' %}">Login</a>
        <a class='btn btn-outline-info  mr-2 btn-sm' href="{% url 'users:register' %}">Register</a>
        {% endif %}
    </nav>
</body>
</html>